// Generated by scripts/generate-lang-packages.py. Do not edit.

/** A language word list: one entry per line of the source list. */
export type WordList = string[];

/** Canonical language codes. */
export type LanguageCode =
  | "cs"
  | "da"
  | "de"
  | "el"
  | "en"
  | "es"
  | "es_419"
  | "fi"
  | "fr"
  | "hu"
  | "id"
  | "it"
  | "ja"
  | "ko"
  | "nl"
  | "no"
  | "pl"
  | "pt"
  | "pt_br"
  | "ro"
  | "ru"
  | "sv"
  | "th"
  | "tr"
  | "uk"
  ;

/** Codes kept for compatibility with badwords 2.x. */
export type LegacyLanguageCode =
  | "br"
  | "cz"
  | "du"
  | "gr"
  | "in"
  | "lt"
  | "po"
  | "sp"
  | "sw"
  | "tu"
  | "ua"
  ;

declare const languages: Record<LanguageCode | LegacyLanguageCode, WordList>;
export default languages;
