[package]
name = "badwords-py"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Python bindings for badwords profanity filter"
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true

[lib]
name = "_native"
crate-type = ["cdylib", "rlib"]

[dependencies]
badwords-core = { workspace = true, features = [
    "fs-resources",
    "embedded-data",
    "embedded-words",
    "substring",
] }
pyo3 = { version = "0.22", features = ["extension-module"] }
