#!/usr/bin/env python3
"""Generate the @badwords/languages npm package from the crate's word lists.

The canonical word lists live in rust/badwords-core/resources/words; this
mirrors them into JSON, along with the alias table from languages.json so that
the pre-3.0 codes keep resolving.

Run: make lang-packages
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
RESOURCES = ROOT / "rust" / "badwords-core" / "resources"
WORDS_DIR = RESOURCES / "words"
REGISTRY = RESOURCES / "data" / "languages.json"
PKG_DIR = ROOT / "js" / "languages"
WORKSPACE_MANIFEST = ROOT / "Cargo.toml"

# Fields the generator owns; anything else in package.json is preserved.
PACKAGE_METADATA: dict[str, Any] = {
    "name": "@badwords/languages",
    "description": "Optional language word lists for badwords-wasm",
    "license": "MIT",
    "repository": {"type": "git", "url": "https://github.com/FlacSy/badwords"},
    "homepage": "https://badwords.flacsy.dev",
    "bugs": "https://github.com/FlacSy/badwords/issues",
    "author": "FlacSy <flacsy.x@gmail.com>",
    "keywords": ["badwords", "profanity", "filter", "languages"],
}


def workspace_version() -> str:
    """Read the version from the Cargo workspace, the single source of truth."""
    text = WORKSPACE_MANIFEST.read_text(encoding="utf-8")
    section = text.split("[workspace.package]", 1)
    if len(section) != 2:
        message = f"no [workspace.package] section in {WORKSPACE_MANIFEST}"
        raise RuntimeError(message)
    match = re.search(r'^\s*version\s*=\s*"([^"]+)"', section[1], re.MULTILINE)
    if match is None:
        message = f"no version found in {WORKSPACE_MANIFEST}"
        raise RuntimeError(message)
    return match.group(1)


def load_registry() -> tuple[dict[str, dict[str, str]], dict[str, dict[str, Any]]]:
    """Canonical languages and the alias table."""
    data = json.loads(REGISTRY.read_text(encoding="utf-8"))
    return data["languages"], data.get("aliases", {})


def write_language_files(languages: dict[str, dict[str, str]]) -> list[str]:
    """Write one JSON array of words per language."""
    lang_dir = PKG_DIR / "lang"
    lang_dir.mkdir(parents=True, exist_ok=True)
    for stale in lang_dir.glob("*.json"):
        stale.unlink()

    written = []
    for code in sorted(languages):
        source = WORDS_DIR / languages[code]["file"]
        words = [
            line.strip()
            for line in source.read_text(encoding="utf-8-sig").splitlines()
            if line.strip()
        ]
        (lang_dir / f"{code}.json").write_text(
            json.dumps(words, ensure_ascii=False, indent=0),
            encoding="utf-8",
        )
        written.append(code)
    return written


def write_index(codes: list[str], aliases: dict[str, dict[str, Any]]) -> None:
    """CommonJS barrel plus its type declarations."""
    lines = [
        "// Generated by scripts/generate-lang-packages.py. Do not edit.",
        "// Prefer @badwords/languages/de over the barrel: it tree-shakes.",
        "module.exports = {",
    ]
    lines.extend(f'  "{code}": require("./lang/{code}.json"),' for code in codes)
    lines.extend(
        f'  "{alias}": require("./lang/{target["target"]}.json"),'
        for alias, target in sorted(aliases.items())
    )
    lines.append("};")
    (PKG_DIR / "index.js").write_text("\n".join(lines) + "\n", encoding="utf-8")

    types = [
        "// Generated by scripts/generate-lang-packages.py. Do not edit.",
        "",
        "/** A language word list: one entry per line of the source list. */",
        "export type WordList = string[];",
        "",
        "/** Canonical language codes. */",
        "export type LanguageCode =",
        *[f'  | "{code}"' for code in codes],
        "  ;",
        "",
        "/** Codes kept for compatibility with badwords 2.x. */",
        "export type LegacyLanguageCode =",
        *[f'  | "{alias}"' for alias in sorted(aliases)],
        "  ;",
        "",
        "declare const languages: Record<LanguageCode | LegacyLanguageCode, WordList>;",
        "export default languages;",
    ]
    (PKG_DIR / "index.d.ts").write_text("\n".join(types) + "\n", encoding="utf-8")

    # Every ./lang/*.json import is an array of strings.
    (PKG_DIR / "lang" / "index.d.ts").write_text(
        "// Generated by scripts/generate-lang-packages.py. Do not edit.\n"
        "declare const words: string[];\n"
        "export default words;\n",
        encoding="utf-8",
    )


def write_package_json(
    codes: list[str],
    aliases: dict[str, dict[str, Any]],
    version: str,
) -> None:
    """Rewrite package.json, preserving fields the generator does not own."""
    target = PKG_DIR / "package.json"
    existing: dict[str, Any] = {}
    if target.exists():
        existing = json.loads(target.read_text(encoding="utf-8"))

    exports: dict[str, Any] = {}
    for code in codes:
        exports[f"./{code}"] = f"./lang/{code}.json"
    for alias, entry in sorted(aliases.items()):
        exports[f"./{alias}"] = f"./lang/{entry['target']}.json"
    exports["."] = {"types": "./index.d.ts", "default": "./index.js"}
    exports["./package.json"] = "./package.json"

    package = {**existing, **PACKAGE_METADATA}
    package["version"] = version
    package["types"] = "./index.d.ts"
    package["exports"] = exports
    package["files"] = ["lang", "index.js", "index.d.ts"]

    target.write_text(json.dumps(package, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def write_readme(
    languages: dict[str, dict[str, str]],
    aliases: dict[str, dict[str, Any]],
    counts: dict[str, int],
) -> None:
    """Document the package, including the alias table."""
    rows = "\n".join(
        f"| `{code}` | {languages[code]['name']} | {counts[code]} |" for code in sorted(languages)
    )
    alias_rows = "\n".join(
        f"| `{alias}` | `{entry['target']}` | {entry.get('note', '')} |"
        for alias, entry in sorted(aliases.items())
    )
    readme = f"""# @badwords/languages

Optional language word lists for [badwords-wasm](https://www.npmjs.com/package/badwords-wasm),
which ships with English and Russian built in.

## Usage

```bash
npm install badwords-wasm @badwords/languages
```

```javascript
import init, {{ ProfanityFilter }} from 'badwords-wasm';
import de from '@badwords/languages/de';
import uk from '@badwords/languages/uk';

await init();
const filter = new ProfanityFilter();
filter.addWords(de);
filter.addWords(uk);

filter.isProfane('some text');
```

TypeScript declarations are included; each import is typed as `string[]`.

## Languages

| Code | Language | Entries |
|------|----------|---------|
{rows}

## Legacy codes

The codes used before 3.0.0 still resolve to the same word lists. The four
below are kept only for compatibility - each one is the ISO 639-1 code of a
*different* language, so prefer the canonical code.

| Code | Resolves to | Note |
|------|-------------|------|
{alias_rows}

Generated by `make lang-packages`.
"""
    (PKG_DIR / "README.md").write_text(readme, encoding="utf-8")


def main() -> None:
    """Regenerate the package."""
    languages, aliases = load_registry()
    version = workspace_version()

    codes = write_language_files(languages)
    counts = {
        code: len(json.loads((PKG_DIR / "lang" / f"{code}.json").read_text(encoding="utf-8")))
        for code in codes
    }
    write_index(codes, aliases)
    write_package_json(codes, aliases, version)
    write_readme(languages, aliases, counts)

    total = sum(counts.values())
    print(
        f"@badwords/languages {version}: {len(codes)} languages, "
        f"{len(aliases)} aliases, {total} entries"
    )


if __name__ == "__main__":
    main()
