name: Release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build-pypi:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment:
      name: pypi
    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          command: build
          args: --release -o dist
          sdist: true
          manylinux: auto

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
